#!/bin/bash

############################################
# This script has the logic for building a
# Docker image based on the Dockerfile.
############################################

docker build -t srp33/phlash_b:v$(cat ../VERSION) .
