#!/bin/bash

## This will execute the container in interactive mode.
## Hit Ctrl-C when you want to close the container.

# Settings described here: https://github.com/tiangolo/meinheld-gunicorn-flask-docker

mkdir -p users
chmod 777 users 
docker run --rm -i -t \
    --name phlash_b \
    -p 5000:5000 \
    -v $(pwd)/users:/app/users  \
    -e PORT=5000 \
    -e WORKERS_PER_CORE="0.5" \
    -e GUNICORN_CONF="/app/custom_gunicorn_conf.py" \
    srp33/phlash_b:v$(cat ../VERSION)
