#!/bin/bash

## This will execute the container in interactive mode.
## Hit Ctrl-C when you want to close the container.
#docker run --rm -i -t --name phlash_b -p 5000:80 --network host \
docker run --rm -i -t --name phlash_b -p 5000:80 \
    srp33/phlash_b:v1

#docker run --rm -i -t --name phlash_b srp33/phlash_b:v1 /bin/bash
